# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galery', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='galery.Category'),
            preserve_default=False,
        ),
    ]
