# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-26 09:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
